server:
  port: 8082

spring:
  application:
    name: post-svc

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: localhost:8848
      config:
        enabled: false
        server-addr: localhost:8848
        file-extension: yml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
